### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by grzesiek2010** [mohamadian/PersianJodaTime#1]
Hi @mohamadian 
I'm a contributor to [ODK Collect](https://github.com/opendatakit/collect). We wanted to use your project to implement the Persian calendar in our app. There is a ready pr: https://github.com/opendatakit/collect/pull/3131

It would be just better if you had a license file that allows us to do that. Could you add it?

**Comment by mohamadian** [comment]
Dear Orczykowski,

I add the license file. It is nice to hear you are trying to develop a Persian calendar. Good luck.

**Comment by yanokwa** [comment]
Thanks so much for adding a license, @mohamadian!

I noticed you chose GPL. Given that this library is based on Joda and zubinkavarana/joda-time, both of which are using the Apache v2 license, I think you can only license your changes to those two projects as GPL.

Independent of that, I think Apache v2 would be preferred because that's what the Joda ecosystem seems to prefer and it'd also enable ODK and others who use Joda to more easily use your great library.

It's your code, so it's your decision, but would you consider a change from GPL to Apache?

**Comment by mohamadian** [comment]
Oh, that's right. I change the license to Apache v2.
